DROP TABLE IF EXISTS `user_roles`;
DROP TABLE IF EXISTS `users`;

CREATE TABLE  `users` (
  `USER_ID` int(10) unsigned NOT NULL,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  `user_roles` (
  `USER_ROLE_ID` int(10) unsigned NOT NULL,
  `USER_ID` int(10) unsigned NOT NULL,
  `AUTHORITY` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  KEY `FK_user_roles` (`USER_ID`),
  CONSTRAINT `FK_user_roles` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO users (USER_ID, USERNAME,PASSWORD, ENABLED)
VALUES (100, 'adarsh', 'radha', TRUE);

INSERT INTO users (USER_ID, USERNAME,PASSWORD, ENABLED)
VALUES (101, 'admin', 'admin', TRUE);

INSERT INTO users (USER_ID, USERNAME,PASSWORD, ENABLED)
VALUES (102, 'user', 'user', TRUE);

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
VALUES (1, (SELECT USER_ID FROM USERS WHERE USERNAME='adarsh'), 'ROLE_SUPERADMIN');

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
VALUES (2, (SELECT USER_ID FROM USERS WHERE USERNAME='admin'), 'ROLE_ADMIN');

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
VALUES (3, (SELECT USER_ID FROM USERS WHERE USERNAME='user'), 'ROLE_USER');