(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var F2=function(a){a.P("cardstatechange",g.oK(a)&&g.pK(a)?1:0)},bra=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Hj&&a.dataset){if(g.uc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Rc("pollChoiceIndex"))},cra=function(a){return Math.pow(a,3)},dra=function(a){return 3*a*a-2*a*a*a},G2=function(a,b){var c=g.go("use_default_events_client")?void 0:g.lq;
(0,g.y)(b,function(d){d={csn:a,ve:g.sr(d),eventType:4};var e={Ik:g.zr(a),Qi:a};"UNDEFINED_CSN"==a?g.Mr("visualElementShown",d,e):c?g.Bp("visualElementShown",d,c,e):g.mq("visualElementShown",d,e)})},H2=function(a,b){var c=g.go("use_default_events_client")?void 0:g.lq;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.sr(d),eventType:e?16:8};e={Ik:g.zr(a),Qi:a,KE:e};"UNDEFINED_CSN"==a?g.Mr("visualElementHidden",d,e):c?g.Bp("visualElementHidden",d,c,e):g.mq("visualElementHidden",d,e)})},K2=function(a){a=g.Ra(a);
delete I2[a];g.A.isEmpty(I2)&&J2&&J2.stop()},fra=function(){J2||(J2=new g.I(function(){era()},20));
var a=J2;a.isActive()||a.start()},era=function(){var a=(0,g.H)();
g.A.forEach(I2,function(b){gra(b,a)});
g.A.isEmpty(I2)||fra()},L2=function(a,b,c,d){g.rn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},gra=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;hra(a,a.progress);1==a.progress?(a.o=0,K2(a),a.md(),a.im()):a.ab()&&a.Rt()},hra=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.G[c]-a.w[c])*b+a.w[c]},ira=function(a,b){g.pe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},M2=function(a,b,c,d,e){L2.call(this,b,c,d,e);
this.element=a},N2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
M2.call(this,a,b,c,d,e)},O2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},jra=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.jp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},P2=function(a){return a.baseUrl||null},Q2=function(a,b){return(0,g.be)((0,g.ic)(a,b,void 0),function(c){return!!c})},kra=function(a,b,c){function d(ac){var Db=ac.hovercardButton;
if(!Db)return null;Db=Db.subscribeButtonRenderer;if(!Db)return null;var Gc=f(Db.unsubscribedButtonText),Eg=f(Db.subscribedButtonText);if(Db.subscribed){var Dg=f(Db.subscriberCountWithUnsubscribeText);var Um=f(Db.subscriberCountText)}else Dg=f(Db.subscriberCountText),Um=f(Db.subscriberCountWithSubscribeText);var Zi=null;return ac.signinEndpoint&&(Zi=g.A.li(ac,"signinEndpoint","webNavigationEndpointData","url"),!Zi)?null:Gc&&(Eg||Zi)?{subscribed:Db.subscribed,subscribeText:Gc,subscribeCount:Dg,unsubscribeText:Eg,
unsubscribeCount:Um,enabled:Db.enabled,signinUrl:Zi,classic:ac.useClassicSubscribeButton}:null}
function e(ac){if(ac){var Db=[],Gc=ac.videoId;Gc&&Db.push("v="+Gc);(Gc=ac.playlistId)&&Db.push("list="+Gc);(ac=ac.startTimeSeconds)&&Db.push("t="+ac);return"/watch?"+Db.join("&")}}
function f(ac){if(!ac)return null;var Db=ac.simpleText;return Db?Db:ac.runs?(0,g.ic)(ac.runs,function(Gc){return Gc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,D=!1,E=null,F=null,G=null,J=null,ma=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(D=g.A.li(l,"browseEndpoint","browseId"))z=D,m="/channel/"+z;n=!1;p="new";(D=!!b.isSubscribe)?E=d(b):F=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.A.li(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(J=f(b.productPrice)),b.additionalFeesText&&(ma=f(b.additionalFeesText)),(n=g.A.li(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.A.li(b,"title","accessibility","accessibilityData","label");var ta=b.endpoint?b.endpoint.clickTrackingParams:null,rc="";if(b.metadata){var Wd=f(b.metadata);Wd&&(rc=Wd)}return{id:"element-"+c,type:k,title:f(b.title),metadata:rc,callToAction:f(b.callToAction),
Kw:b.image,iconUrl:G,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:E,subscribersText:F,isSubscribe:D,targetUrl:m,jG:n,Ob:{itct:ta},SO:p,Ak:a?a:null,nG:b.isPlaceholder,impressionUrls:Q2(b.impressionUrls||[],P2),bG:Q2(b.hovercardShowUrls||[],P2),clickUrls:Q2(l.loggingUrls||[],P2),visualElement:g.qr(b.trackingParams),productPrice:J,
additionalFeesText:ma}},R2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=Q2(a.impressionUrls||[],P2);a.trackingParams&&(c.visualElement=g.qr(a.trackingParams));c.elements=Q2(a.elements||[],function(d,e){return kra(b,d,e)});
return c},S2=function(a){g.MK.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.O();this.J=g.Gy(a)||g.Iy(a);this.M=!0;this.G=0;this.B=new g.P(this);g.C(this,this.B);this.B.L(this.player,g.WC("creatorendscreen"),this.ZG);this.B.L(this.player,"crx_creatorendscreen",this.aH);this.B.L(this.player,"resize",this.Ty);this.B.L(window,"focus",this.QN);this.load();var b=g.Vd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.me(this,function(){g.ae(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},lra=function(a){return a.player.getVideoData().Ec?"current":a.J?"new":"current"},T2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},U2=function(a,b,c){c=void 0===c?!0:c;
g.NP(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&mra(a);c=[];d=new g.TC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.w=new g.S({D:"div",I:"ytp-ce-shadow"}),g.zK(a.player,a.w.element,4),a.C=new g.gL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=nra(a,e);a.o[e.id]=f;a.F[e.id]=e;g.zK(a.player,f.element,4);var k=new g.TC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);ora(a,f,e)}g.vK(a.player,c);
a.Ty()}},mra=function(a){var b=g.wr(),c=g.yr();
c&&b&&a.u.visualElement&&g.Sr(c,b,a.u.visualElement)},nra=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:V2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:W2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.Lm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.S(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:V2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:W2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.Lm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.S(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],N:{href:W2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Lm(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:V2(b)}]};c=new g.S(c);var d=g.Hd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Ob.itct}else e="endscreen",f=null;e=new g.bP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",N:{dir:g.Lm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],N:{href:W2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:V2(b)},{D:"div",I:"ytp-ce-expanding-icon",N:pra(b.iconUrl)}]};c=new g.S(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.Ak||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",N:{dir:g.Lm(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:W2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:V2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.S(c)}b.nG&&g.K(c.element,"ytp-ce-placeholder");return c},V2=function(a){if(a.Kw)var b=a.Kw.thumbnails;
return pra(b?b[b.length-1].url:null)},pra=function(a){return a?{style:"background-image: url("+a+")"}:{}},ora=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ka("mouseenter",(0,g.x)(a.Us,a,b,c));b.ka("mouseleave",(0,g.x)(a.Vt,a,b,c));a.player.O().o||b.ka("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ka("click",(0,g.x)(a.xA,a,c));b.ka("keypress",(0,g.x)(a.xA,a,c));b.ka("focus",(0,g.x)(function(l,m){this.Us(l,m)},a,b,c));
b.ka("blur",(0,g.x)(function(l,m){this.Vt(l,m)},a,b,c));
b.ka("touchstart",(0,g.x)(a.Us,a,b,c));var f=g.Jd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.pn(b.element,"ytp-ce-element-hover");g.pn(b.element,"ytp-ce-force-expand")});
b.ka("keydown",(0,g.x)(function(l,m){this.M=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),X2(this,m.id,!0)):(g.pn(l.element,"ytp-ce-force-expand"),g.pn(l.element,"ytp-ce-element-hover"),X2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ka("blur",g.Sa(function(){"none"!=m.style.display&&a.M&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Jd("ytp-sb-subscribe",b.element));c(g.Jd("ytp-sb-unsubscribe",b.element));b.ka("focus",d);b.ka("blur",e)},W2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.gz(c)+b}else return"";return b},X2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},Y2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||T2(a))c&&c();else{b=qra(a,b);var e=0,f=!1,k=new g.I(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.yq(b[a],d)}},Z2=function(a,b,c){Y2(a,b.clickUrls,c);
(a=g.yr())&&b.jG&&g.Pr(a,b.visualElement)},qra=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(rra(b[e],c));return d},rra=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},sra=function(a){return g.Ma(a)&&a.length?a[0]:a},$2=function(a){return"string"===typeof a?a:""},a3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},ura=function(a){var b=tra;
if(null==a)return null;if(g.Na(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},vra=function(a){this.externalId=a},wra=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},b3=function(a){if(!a)return null;
var b=g.cc($2(a.value));b=g.$b(b);if(!b)return null;var c=a3(a.target,xra,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new wra(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},c3=function(a){return a.value?a.value:null},yra=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},tra=function(a){if(!a)return null;
var b=a3(a.type,zra),c=a3(a.trigger,Ara),d=sra(a.url);d=b3(d?d:null);a=sra(a.subscribeData);var e=a?a:null;e?(a=$2(e.external_user_id),e=$2(e.subscription_token),a=a&&e?new vra(a):null):a=null;return b?new yra(b,c,d,a):null},d3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Bra=function(a,b){return g.Za(a.o,b,void 0)},Cra=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Dra=function(a,b){this.merchant=a;
this.price=b},Era=function(a){this.o=a},Fra=function(a,b,c){b&&(c?e3(a,(0,g.ic)(b,g.Sa(function(d,e){return g.Jm(e,d)},c))):e3(a,b))},e3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.yq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Gra=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.A=c;this.videoData=d;this.logger=e;this.U=f;this.u=k},f3=function(a,b){this.o=a;
this.w=b},Jra=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Hra(b,k))},a);
var d={D:"ul",N:{role:"radiogroup"},K:c},e={};b.Ui&&(e["aria-label"]=g.ML("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[g3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Ui&&(f.push("iv-card-unavailable"),d.push({D:"div",Y:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",Y:["iv-card-sign-in-button","iv-button"],N:{href:c3(b.Ui)},K:[{D:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.S({D:"div",
Y:f,K:d});d=f.element;Ira(b,d);jra(a.o.o,d,g.Sa(a.A,b),a);(0,g.y)(g.Id("iv-card-poll-choice-input",d),function(k){this.o.o.ka(k,"focus",g.Sa(this.u,!0));this.o.o.ka(k,"blur",g.Sa(this.u,!1))},a);
b.Ui&&(d=g.Jd("iv-card-sign-in-button",d),a.w(d,b.Ui,b.id,b.Ob,b.Nc.click,5));return f},Kra=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.kP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.mG&&b.gw?{D:"span",Y:d,N:e,W:b.gw}:"";c={D:"div",Y:["iv-card",c],K:[{D:"a",I:"iv-click-target",N:{href:c3(b.url)},K:[h3(b.Zi,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},i3(a,b)]}]}]};c=new g.S(c);j3(a,g.Id("iv-click-target",c.element),b,b.url);return c},k3=function(a){return a.customMessage?
g3("div","iv-card-message",a.customMessage):""},h3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",N:{style:c},K:d}},i3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(g3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Hra=function(a,b){return{D:"li",
I:Cra(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},g3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},g3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ma(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.Lm(c);return{D:a,N:b,W:c}},Lra=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.yn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.yn+");");c.dir=g.Lm(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",Y:b,N:c,K:d}},Ira=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Jd(Cra(a,e.index),b);e=e.count/c;null==a.Ie&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ie==d);f.getElementsByTagName("input")[0].checked=a.Ie==d;var k=Math.floor(100*e).toFixed(0),l=g.Jd("iv-card-poll-choice-percent",f);g.ee(l,g.ML("$PERCENT%",{PERCENT:k}));f=g.Jd("iv-card-poll-result-bar",f);g.bh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.Ie);g.L(b,"iv-card-poll-expanded",
null!=a.Ie&&1<a.choices.length)},j3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Ob,c.Nc.click,5)},a)},Mra=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Nra=function(a,b){return b?b:Mra(a)?"current":"new"},l3=function(a,b){g.B.call(this);
var c=this;this.o=a;this.context=b;this.Xu=!1;this.na=new Map;this.ra=new Map;this.context.U.addEventListener(g.WC("annotations_module"),function(d){(d=c.na.get(d))&&d.apply(c)});
this.context.U.addEventListener("crx_annotations_module",function(d){(d=c.ra.get(d))&&d.apply(c)})},Ora=function(a,b,c,d,e){var f=c3(b);
if(f){var k=Nra(f,b.target),l=(0,g.x)(function(){b.o&&this.context.U.pauseVideo();var m=this.context.videoData.Ec||!1,n=g.Ip(f||"");m&&n&&(n.v||n.list)?g.FS(this.context.U.app,n.v,c,n.list,!1,void 0):g.QL(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);e3(a.context.logger,d,l,e);Mra(f)||(a=g.yr(),d=c.itct,a&&d&&g.Pr(a,g.qr(d)))}},Pra=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},m3=function(a,b,c){return{Ux:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
lC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
gq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},p3=function(a,b,c){l3.call(this,b,c);
var d=this;this.w=a;this.da=this.Ha=this.C=this.Ga=!1;this.ea=null;this.aa=new g.I(g.Ja,c.A.Na?4E3:3E3);g.C(this,this.aa);this.ya=new g.I(g.Ja);g.C(this,this.ya);this.H=new f3(c,(0,g.x)(this.hk,this),(0,g.x)(this.Ho,this));this.T=new g.S({D:"div",I:"iv-drawer",N:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.C(this,this.T);this.F=this.T.element;this.sa=new g.gL(this.T,330);g.C(this,this.sa);this.Ba=g.Jd("iv-drawer-header-text",this.F);this.B=g.Jd("iv-drawer-content",this.F);this.A=[];this.Aa=this.R=this.G=this.ha=this.u=null;this.Z=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ha&&n3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ha=d.C)&&o3(d)});
this.V=this.J=this.ca=null;this.M=0},Qra=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){n3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){o3(a)});
var c=b.data.headerText;g.ee(a.Ba,c);a.R&&a.R.setAttribute("title",c);a.ca=g.qr(b.data.trackingParams);a.V=g.qr(b.data.closeTrackingParams);a.J=g.qr(b.data.iconTrackingParams)},Rra=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.M;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"simple",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:q3(a,c,b,d),sponsored:!1,Nc:m3(d,e,d.command),ke:d.trackingParams?g.qr(d.trackingParams):null,de:e.trackingParams?
g.qr(e.trackingParams):null,Ed:f&&f.trackingParams?g.qr(f.trackingParams):null,imageUrl:r3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.W(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,yn:null,title:d.title?g.W(d.title):"",customMessage:d.callToAction?g.W(d.callToAction):"",url:d.command.urlEndpoint.url?b3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};s3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"collaborator",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:q3(a,c,b,d),sponsored:!1,Nc:m3(d,e,d.endpoint),ke:d.trackingParams?g.qr(d.trackingParams):null,de:e.trackingParams?g.qr(e.trackingParams):null,Ed:f&&f.trackingParams?
g.qr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.W(d.customText):null,qB:r3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.W(d.channelName):"",metaInfo:[d.subscriberCountText?g.W(d.subscriberCountText):""],url:b3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};s3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"playlist",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:q3(a,c,b,d),sponsored:!1,Nc:m3(d,e,d.action),ke:d.trackingParams?g.qr(d.trackingParams):null,de:e.trackingParams?g.qr(e.trackingParams):null,Ed:f&&f.trackingParams?g.qr(f.trackingParams):
null,Zi:r3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.W(d.customMessage):null,playlistVideoCount:g.W(d.playlistVideoCount),title:d.playlistTitle?g.W(d.playlistTitle):"",metaInfo:[d.channelName?g.W(d.channelName):"",d.videoCountText?g.W(d.videoCountText):""],url:b3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Pra(d.action)})};s3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"video",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:q3(a,c,b,d),sponsored:!1,Nc:m3(d,e,d.action),ke:d.trackingParams?g.qr(d.trackingParams):null,de:e.trackingParams?g.qr(e.trackingParams):null,Ed:f&&f.trackingParams?g.qr(f.trackingParams):null,Zi:r3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.W(d.lengthString):null,customMessage:d.customMessage?g.W(d.customMessage):null,title:d.videoTitle?g.W(d.videoTitle):"",metaInfo:[d.channelName?g.W(d.channelName):"",d.viewCountText?g.W(d.viewCountText):""],isLiveNow:!!d.badge,url:b3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Pra(d.action)})};s3(a,c)}a.M++},r3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},q3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},Tra=function(a,b){var c=Sra(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.ae(c.Zq),g.fb(a.A,c),a.Bn(),t3(a))},n3=function(a,b,c){if(!a.C){a.sa.show();
a.ha=new g.I(function(){g.K(g.fK(a.context.U),"ytp-iv-drawer-open")},0);
a.ha.start();a.ea=g.ap(a.B,"mousewheel",(0,g.x)(a.nH,a));a.C=!0;var d=g.yr();d&&a.ca&&a.V&&G2(d,[a.ca,a.V]);var e=g.A.create("TRIGGER_TYPE",b);(0,g.y)(a.A,function(f){f.zy||(f.zy=!0,Fra(a.context.logger,f.card.Nc.Ux,e));d&&G2(d,[f.card.ke])});
F2(a.w);c&&(a.G=new g.I(function(){a.xa=a.R;a.Aa.focus()},330),a.G.start())}},o3=function(a){a.C&&(a.sa.hide(),g.bp(a.ea),a.ea=null,g.pn(g.fK(a.context.U),"ytp-iv-drawer-open"),a.C=!1,F2(a.w),a.G&&a.G.stop(),a.G=new g.I(function(){a.xa&&(a.xa.focus(),a.xa=null)},330),a.G.start())},Ura=function(a){var b=g.Jd("iv-drawer-close-button",a.F);
a.context.o.ka(b,"click",a.qE,a);a.context.o.ka(a.B,"touchend",function(){a.aa.start()});
a.context.o.ka(a.B,"scroll",a.GE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.nn(g.fK(a.w),"ytp-autohide")});
a.Z.push(g.xo("iv-button-shown",a.uG,a));a.Z.push(g.xo("iv-button-hidden",a.tG,a));a.Z.push(g.xo("iv-teaser-shown",a.xG,a));a.Z.push(g.xo("iv-teaser-hidden",a.wG,a));a.Z.push(g.xo("iv-teaser-clicked",a.vG,a))},s3=function(a,b){a.Ga||(g.on(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.zK(a.w,a.F,5),Ura(a),a.R=g.Jd("ytp-cards-button",g.fK(a.w)),a.Aa=g.Jd("iv-drawer-close-button",a.F),a.Ga=!0);Tra(a,b.id);var c=Vra(a,b);if(c){var d={card:b,Zq:c.element,zy:!1},e=Wra(a,d);g.nb(a.A,e,0,d);c.ba(a.B,e);a.Bn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.DO,d)):(c=1E3*a.context.U.getCurrentTime(),5E3>c&&c>b.startMs&&a.VB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.VB,d)),t3(a))}},Vra=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=Lra(b);d={D:"div",Y:["iv-card"],K:[{D:"a",I:"iv-click-target",N:{href:c3(b.url)},K:[h3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[g3("h2",void 0,b.title),e]}]}]};d=new g.S(d);j3(c,g.Id("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",Y:["iv-card","iv-card-channel"],K:[{D:"a",Y:["iv-click-target"],N:{href:c3(b.url),"data-ytid":b.channelId},K:[h3(b.qB),{D:"div",I:"iv-card-content",
K:[k3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},i3(c,b)]}]}]},d=new g.S(d),j3(c,g.Id("iv-click-target",d.element),b,b.url),d;case "episode":return Kra(a.H,b,"iv-card-episode");case "movie":return Kra(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",Y:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",N:{href:c3(b.url)},K:[h3(b.Zi,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[k3(b),
g3("h2","iv-card-primary-link",b.title),i3(c,b)]}]}]},d=new g.S(d),j3(c,g.Id("iv-click-target",d.element),b,b.url),d;case "poll":return Jra(a.H,b);case "productListing":c=a.H;var f=!g.cb(b.offers);d=["iv-card"];e="";var k=Lra(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",Y:d,N:{tabindex:"0"},K:[{D:"a",
Y:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:c3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",N:{href:c3(b.url)},K:[g3("h2",e,b.title),k]}]}]};d=new g.S(d);
e=g.Vd("span");g.ee(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.kb(e,"adInfo");j3(c,g.Id("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",N:{href:c3(b.url)},K:[h3(b.Zi,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[k3(b),g3("h2","iv-card-primary-link",b.title),i3(c,b),d]}]}]},d=new g.S(d),j3(c,g.Id("iv-click-target",d.element),b,b.url),d}return null},Wra=function(a,b){if(0==a.A.length)return 0;
var c=g.$a(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Xra=function(a){return a.u?"productListing"==a.u.card.type:(0,g.ai)(a.A,function(b){return"productListing"==b.card.type})},t3=function(a){g.L(g.fK(a.w),"ytp-cards-shopping-active",Xra(a))},Yra=function(a,b){if(a.T.Fa()){var c=new L2([0,
a.B.scrollTop],[0,b.Zq.offsetTop],600,dra);a.context.w.ka(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ka(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.cu(a.T,!0),a.B.scrollTop=b.Zq.offsetTop,g.cu(a.T,!1)},u3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Sra=function(a,b){return g.Za(a.A,function(c){return c.card.id==b})},v3=function(a,b,c){l3.call(this,a,b);
this.annotation=c;this.isActive=!1},Zra=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},w3=function(a,b,c){v3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},x3=function(a,b,c){v3.call(this,a,b,c);
this.J=this.C=this.M=!1;this.G=5E3;this.B=null;this.H=g.Ud("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.I(function(){this.u.setAttribute("aria-hidden",!0);g.vh(this.A,!1);g.vh(this.w,!0)},700,this);
g.C(this,this.F)},$ra=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=a.annotation.Vb(),f=b.image_url;if(f){var k=g.Ud("DIV",["iv-promo-img","iv-click-target"]);f=g.Ud("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Ud("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Ud("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.hk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Ud("A","iv-promo-txt"),g.Ec(f,c3(e)),a.u=f):a.u=g.Ud("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_1));var m=g.Ud("P",null,g.Ud("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.T(a.context.A.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Ud("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Ud("BUTTON",["iv-button","iv-promo-button"],g.Ud("SPAN","iv-button-content",f));var p=g.Ud("DIV","iv-promo-button-container");p.appendChild(f);e&&a.hk(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.hk(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Ud("P",null,g.Ud("SPAN",null,b.text_line_1)),
m=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Ud("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.hk(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);p&&a.H.appendChild(p);c=g.Ud("DIV","iv-promo-actions");a.w=g.Ud("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ka(a.w,"click",g.Sa(a.Wr,5E3),a);c.appendChild(a.w);g.vh(a.w,!1);
a.context.o.ka(a.o,"mouseover",a.EF,a);a.context.o.ka(a.o,"mouseout",a.DF,a);a.context.o.ka(a.o,"touchend",g.Sa(a.Wr,5E3),a);a.A=g.Ud("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ka(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.wF:a.vF,a);c.appendChild(a.A);g.on(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},asa=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},bsa=function(a){a.F.stop();
a.C&&(g.qn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.vh(a.w,!1),g.vh(a.A,!0))},csa=function(a,b){a.B||(a.B=g.zf(function(){y3(this);
asa(this)},b,a))},y3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},z3=function(a){g.MK.call(this,a);
this.J=!1;this.H=0;this.F={};this.T=new Era(a);this.B=new g.P(this);g.C(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.P,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.P,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.P,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.P,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.P,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.mM,this);this.subscribe("resize",this.xp,this);this.player.O().F.subscribe("vast_info_card_add",this.bB,this);this.R=new g.P(this);g.C(this,this.R);this.V=g.Ud("DIV","video-custom-annotations");this.u=new g.S({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.zK(this.player,this.u.element,4);this.u.hide();this.A=new g.S({D:"div",Y:["ytp-iv-video-content"]});g.C(this,this.A);g.Yd(this.A.element,g.Ud("DIV","video-annotations",
this.V));this.G=this.o=null;this.M=[];dsa(this)&&this.load();var b=g.Vd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.me(this,function(){g.ae(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},esa=function(){var a=g.Ud("DIV",["annotation",
"annotation-type-custom"]);g.vh(a,!1);return a},fsa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},dsa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.OC||b.F.get(a.videoId)||g.zB(a)||g.AB(a)?!0:!1},gsa=function(a,b,c){a.J=!0;
a.C=g.$p(b,c)},hsa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(hsa(a,e))}return c},isa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},lsa=function(a){var b=a.player.getVideoData();
if(b.he){var c=a.player.O().F.get(b.videoId);if(c){var d={format:"XML",fe:{},method:"POST",withCredentials:!0};d.md=(0,g.x)(function(e,f,k){isa(this,e,f)||(e=g.Up(k)&&k.responseXML?k.responseXML:null)&&A3(this,e)},a,a.H,b.videoId);
g.rp()&&(d.md=jsa(a,d.md));d.ub={ic_only:"1"};ksa(d,c);a.J=!0;g.$p(b.he,d)}}},ksa=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Fn&&(a.ub.ic_coll=b.Fn);b.Gn&&(a.ub.ic_xml=b.Gn);b.Mm&&(a.ub.ic_track=b.Mm)},msa=function(a){var b=new g.S({D:"div"});
g.vh(b.element,!1);var c=new p3(a.player,b.element,B3(a));g.C(c,b);b.ba(a.u.element);c.Am();return c},B3=function(a){if(!a.G){var b=new O2(a);
g.C(a,b);var c=new g.N1(a);g.C(a,c);a.G=new Gra(b,c,a.player.O(),a.player.getVideoData(),a.T,a.player,a.yc)}return a.G},A3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.yr();if(e){var f=g.wr();f&&g.Nr(g.go("use_default_events_client")?void 0:g.lq,e,f,[g.qr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=hsa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=a3(k.type,nsa),t=a3(k.style,osa),u=$2(k.data),z=0!=u.length?JSON.parse(u):{},D=ura(k.action);f=n&&p?new d3(n,p,t,D,z):null}else f=null}catch(ma){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var E=esa(),F=null;switch(m.type){case "branding":if(k.player.O().sa)break;k.u.element.appendChild(E);F=new w3(E,B3(k),m);break;case "promotion":g.zK(k.player,E,4),F=new x3(E,B3(k),m)}F&&F.Am();if(k=F)g.C(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=msa(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,F=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Ux:k.impression,click:k.click,close:k.close,lC:k.teaser_impression,gq:k.teaser_click},m=
f.data.tracking_params||{},E=null,F){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,qB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:b3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,
Ed:m.icon?g.qr(m.icon):null,Zi:f.data.image_url,gw:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,mG:!!f.data.is_paygated,kP:!!f.data.user_has_entitlement,url:b3({target:f.data.target||"new",value:f.data.url})};s3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,Zi:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:b3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,title:f.data.title,choices:f.data.choices,Ie:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Ui:f.data.signin_url?b3({target:"current",value:f.data.signin_url}):null,vP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};s3(c,f);break;case "productListing":f.data.signin_url&&
(E=b3({target:"current",value:f.data.signin_url}));F=[];for(var G=f.data.offers||[],J=0;J<G.length;J++)F.push(new Dra(g.Nc(G[J].merchant),g.Nc(G[J].price)));f={FT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:b3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Ui:E,gU:f.data.signin_title?f.data.signin_title:null,fU:f.data.signin_message?f.data.signin_message:null,offers:F};s3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:b3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,ke:m.card?g.qr(m.card):null,de:m.teaser?
g.qr(m.teaser):null,Ed:m.icon?g.qr(m.icon):null,Zi:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:b3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},s3(c,f)}}else Qra(a.o,f);c=!0}}}c&&(F2(a.player),a.xp())},psa=function(a,b){var c=!1;
a.o||(a.o=msa(a),g.C(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())Rra(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.W(b.headerText):"",g.ee(c.Ba,d),c.R&&c.R.setAttribute("title",d),c.ca=b.trackingParams?g.qr(b.trackingParams):null,c.V=b.closeButton.infoCardIconRenderer.trackingParams?g.qr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.qr(b.icon.infoCardIconRenderer.trackingParams):null,F2(a.player),a.xp())},
qsa=function(a,b,c,d,e){if(!a.player.O().sa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new yra("openUrl","click",new wra("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.W(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.W(b.subscriberCountText))):(b.subscriberCountText&&(e=g.W(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.W(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.W(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.W(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new d3(c,"branding","branding",f,d);d=esa();a.u.element.appendChild(d);f=new w3(d,B3(a),f);f.Am();g.C(f,f);a.F[c]=f}},jsa=function(a,b){return(0,g.x)(function(){if(!this.ga()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.M.push(g.pp(b))}},a)},I2={},J2=null;g.Ua(L2,g.rn);g.h=L2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(this.ab())return!1;K2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.tp();this.ze("play");-1==this.o&&this.ze("resume");this.o=1;var b=g.Ra(this);b in I2||(I2[b]=this);fra();gra(this,a);return!0};
g.h.stop=function(a){K2(this);this.o=0;a&&(this.progress=1);hra(this,this.progress);this.ze("stop");this.im()};
g.h.pause=function(){this.ab()&&(K2(this),this.o=-1,this.ze("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.ze("destroy");L2.Fb.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Rt=function(){this.ze("animate")};
g.h.ze=function(a){this.dispatchEvent(new ira(a,this))};
g.Ua(ira,g.pe);g.Ua(M2,L2);M2.prototype.A=g.Ja;M2.prototype.Rt=function(){this.A();M2.Fb.Rt.call(this)};
M2.prototype.im=function(){this.A();M2.Fb.im.call(this)};
M2.prototype.tp=function(){this.A();M2.Fb.tp.call(this)};
g.Ua(N2,M2);N2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(O2,g.B);O2.prototype.ka=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.ap(a,b,c);this.o.push(a);return a};
O2.prototype.Is=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.kp(a,b,c);this.o.push(a);return a};
O2.prototype.Va=function(a){g.bp(a);g.fb(this.o,a)};
O2.prototype.X=function(){g.bp(this.o);this.o.length=0;g.B.prototype.X.call(this)};g.r(S2,g.MK);g.h=S2.prototype;g.h.load=function(){g.MK.prototype.load.call(this);if(!T2(this)){var a=g.yB(this.player.getVideoData());if(a)a=R2(a,lra(this)),U2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",md:(0,g.x)(this.YK,this,a),fe:{v:a},withCredentials:!0};this.J&&(a.fe.ptype="embedded");var c=this.player.getVideoData().Rn;c&&(a.ub={ad_tracking:c});if(b=g.xB(b))if(b=g.cc(b),b=g.$b(b))this.A=g.$p(b,a)}}};
g.h.unload=function(){U2(this,null);this.A&&(this.A.abort(),this.A=null);g.MK.prototype.unload.call(this)};
g.h.Qc=function(a,b){if(!T2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=R2(b,"new");U2(this,c);return!0}return null};
g.h.getOptions=function(){return T2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.YK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=R2(c,lra(this)))}U2(this,c)};
g.h.Ty=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<rsa.length;f++){var k=Math.abs(b.width-rsa[f]);if(-1==e||d>=k)e=f,d=k}d=ssa[e];this.w&&g.bh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.th(e.element,Math.round(k.width*a.width),f);g.jh(e.element,m,n);g.qn(e.element,tsa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qn(e.element,ssa);g.K(e.element,d);(e=g.Hd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.bh(e,"height",f+"px")}}}}};
g.h.ZG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())Y2(this,this.u.impressionUrls),(a=g.yr())&&this.u.visualElement&&g.Or(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.fK(this.player),"ytp-ce-shown");Y2(this,c.impressionUrls);(b=g.yr())&&g.Or(b,c.visualElement);this.player.O().Eb&&this.player.ma("endscreenelementshown",a)}};
g.h.aH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.pn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.pn(g.fK(this.player),"ytp-ce-shown");this.player.O().Eb&&this.player.ma("endscreenelementhidden",a)}};
g.h.QN=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c in b.o)g.qn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.xA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.nn(c,"ytp-ce-element");){g.nn(c,"subscribe-label")&&Z2(this,a);if(g.nn(c,"ytp-ce-channel-subscribe"))return;c=g.ce(c)}if(!c||g.nn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Vt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.SO?(Z2(this,a),this.UB(),this.player.pauseVideo(),c=g.cc(W2(this,a.targetUrl)),c=g.$b(c),g.QL(c,void 0,a.Ob)):(c=this.player.getVideoData().Ec,
c=(0,g.x)(this.MO,this,c,W2(this,a.targetUrl),a.Ob),c=(0,g.x)(this.UB,this,c),Z2(this,a,c))}}};
g.h.MO=function(a,b,c){var d=g.Ip(b);a&&d&&(d.v||d.list)?g.FS(this.player.app,d.v,c,d.list,!1,void 0):g.PL(b,c)};
g.h.Us=function(a,b){g.nn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.I(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),Y2(this,b.bG),X2(this,b.id,!0))};
g.h.Vt=function(a,b){g.pn(a.element,"ytp-ce-element-hover");g.pn(a.element,"ytp-ce-force-expand");X2(this,b.id,!1)};
g.h.UB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var rsa=[346,426,470,506,570,640,853,1280,1920],ssa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),tsa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var xra={AQ:"current",XR:"new"};var zra={CLOSE:"close",aS:"openUrl",LD:"subscribe"},Ara={uQ:"click",CLOSE:"close",nR:"hidden",FS:"rollOut",GS:"rollOver",JS:"shown"};d3.prototype.Vb=function(){var a=Bra(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var osa={XP:"anchored",fD:"branding",CHANNEL:"channel",zQ:"cta",pR:"highlightText",GR:"label",PLAYLIST:"playlist",sS:"popup",NS:"speech",LD:"subscribe",YS:"title",VIDEO:"video",lT:"website"},nsa={fD:"branding",lQ:"card",HQ:"drawer",oR:"highlight",NR:"marker",xS:"promotion",TEXT:"text",nT:"widget"};f3.prototype.u=function(a,b){var c=g.je(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
f3.prototype.A=function(a,b){var c=g.je(b.target,null,"iv-card-poll",void 0);if(c)if(a.Ui)g.Jd("iv-card-sign-in-button",c).click();else{var d=parseInt(bra(b.target),10);if(null==a.Ie)a.choices[d].count++,a.Ie=d;else if(a.Ie!=d){var e=a.choices[a.Ie];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ie=d}else e=a.choices[a.Ie],e.count=Math.max(e.count-1,0),a.Ie=null;Ira(a,c);g.dq(this.o.videoData.he,{fe:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.vP}});e3(this.o.logger,a.Nc.click,
void 0,5);(c=g.yr())&&a.ke&&g.Pr(c,a.ke)}};g.r(l3,g.B);g.h=l3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.TC(a,b,{id:c});a.namespace="annotations_module";d&&this.na.set(a,d);e&&this.ra.set(a,e);g.vK(this.context.U,[a])};
g.h.Am=function(){this.context.u.subscribe("resize",this.Bn,this)};
g.h.hk=function(a,b,c,d,e,f){this.context.o.ka(a,"click",g.Sa(this.Ho,b,c,d,e||[],f||0),this);this.context.o.ka(a,"touchstart",g.Sa(function(){this.Xu=!1}),this);
this.context.o.ka(a,"touchmove",g.Sa(function(){this.Xu=!0}),this)};
g.h.Ho=function(a,b,c,d,e,f){if(this.Xu)return!1;f&&(f.stopPropagation(),f.preventDefault());Ora(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.ae(this.o)};
g.h.Bn=function(){};
g.h.X=function(){this.na.clear();this.ra.clear();g.B.prototype.X.call(this)};g.r(p3,l3);g.h=p3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.fK(this.w))?(a=g.uh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Bn=function(){var a=this.isAvailable();g.vh(this.o,a);g.L(g.fK(this.context.U),"ytp-iv-drawer-enabled",a);F2(this.w)};
g.h.destroy=function(){var a=g.nK(g.aK(this.w));a&&a.Qs(!1,void 0);try{g.fK(this.w).removeChild(this.F)}catch(b){}g.yo(this.Z);g.bp(this.ea);this.ha&&this.ha.dispose();this.G&&this.G.dispose();l3.prototype.destroy.call(this)};
g.h.nH=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.VB=function(a){if(!g.nn(g.fK(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.yr(),c=this.u?this.u.card.Ed:this.J;b&&c&&H2(b,[c]);this.u=a;t3(this)}if(b="none"!=this.o.style.display)2==this.context.U.getPresentingPlayerType()?b=1==this.context.U.getAdState():(b=this.context.U.getPlayerState(),c=0==b&&0===this.context.U.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.nK(g.aK(this.w)))&&c.Qs(!0,b));this.ya.isActive()||
((!this.C||!this.aa.isActive()&&this.da)&&Yra(this,a),this.ya.start(910+a.card.teaserDurationMs))}};
g.h.DO=function(a){this.C||(this.u=a,t3(this),Yra(this,a),n3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.qE=function(){if(this.C){e3(this.context.logger,u3(this).Nc.close);var a=g.yr();a&&this.V&&g.Pr(a,this.V);o3(this)}};
g.h.GE=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.uG=function(){var a=g.yr(),b=u3(this);b=b?b.Ed:this.J;a&&b&&G2(a,[b])};
g.h.tG=function(){var a=g.yr(),b=u3(this);b=b?b.Ed:this.J;a&&b&&H2(a,[b])};
g.h.xG=function(){var a=u3(this);e3(this.context.logger,a.Nc.lC);var b=g.yr();b&&a&&G2(b,[a.de,a.Ed])};
g.h.wG=function(){var a=g.yr(),b=u3(this);a&&b&&H2(a,[b.de])};
g.h.vG=function(a){var b=u3(this),c=g.yr();this.u?a?(a=this.context.logger,e3(a,b.Nc.gq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.de&&g.Pr(c,b.de)):(a=this.context.logger,e3(a,b.Nc.gq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Ed&&g.Pr(c,b.Ed)):(a=this.context.logger,e3(a,b.Nc.gq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.Pr(c,this.J))};g.r(v3,l3);v3.prototype.Am=function(){l3.prototype.Am.call(this);Zra(this)};
v3.prototype.show=function(){l3.prototype.show.call(this);var a=g.yr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&G2(a,[g.qr(b.itct)])};
v3.prototype.hide=function(){l3.prototype.hide.call(this);var a=g.yr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&H2(a,[g.qr(b.itct)])};g.r(w3,v3);g.h=w3.prototype;g.h.NO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.uh(a);this.u||(g.sh(a,e.width),g.sh(b,e.width));g.bh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.bh(c,"right","1px");this.B=!0;g.vh(a,!0);this.C=new g.I(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.aG=function(a,b){g.pn(this.o,"iv-branding-active");this.F=new g.I((0,g.x)(function(){g.vh(a,!1);this.u||g.sh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){v3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Ud("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.vh(this.w,!1);var b=g.Ud("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=this.annotation.Vb())&&this.hk(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Ud("DIV","iv-branding-context-name");
g.ee(c,a.channel_name);var d=g.Ud("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.bP(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.U),this.u.ba(d);b=g.Ud("DIV","iv-branding-context-subscribe-caret");c=g.Ud("DIV","branding-context-container-inner",b,c,d);g.vh(c,!1);d=g.Ud("DIV","branding-context-container-outer",c);g.bh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.I(g.Sa(this.aG,c,d),500,this);g.C(this,this.A);this.context.o.ka(this.o,"mouseover",(0,g.x)(this.NO,this,c,d,b,a.image_height));this.context.o.ka(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.vh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.nh(a);c=g.uh(a);b=(new g.Zg(b.x,b.y,c.width,c.height)).width;g.jh(a,b);e=new N2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,cra);g.C(this,e);this.context.w.ka(e,
"begin",g.Sa(g.vh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(v3.prototype.hide.call(this),g.vh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);v3.prototype.destroy.call(this)};g.r(x3,v3);g.h=x3.prototype;g.h.show=function(){this.isActive||(v3.prototype.show.call(this),this.M||($ra(this),this.M=!0),g.vh(this.o,!0),g.zf(function(){g.pn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,y3(this),bsa(this),csa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Ho=function(a,b,c,d,e,f){return this.C?!1:v3.prototype.Ho.call(this,a,b,c,d,e,f)};
g.h.Wr=function(a,b){b.stopPropagation();bsa(this);csa(this,a);this.u.focus()};
g.h.EF=function(a){this.J=!0;this.Wr(500,a)};
g.h.DF=function(){this.J=!1;asa(this)};
g.h.vF=function(a){a.stopPropagation();this.hide()};
g.h.wF=function(a){a.stopPropagation();y3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();v3.prototype.destroy.call(this)};g.r(z3,g.MK);g.h=z3.prototype;g.h.Qc=function(a,b){if(!fsa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.M1(b);c&&A3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Tra(this.o,b),F2(this.player)),!0}return null};
g.h.getOptions=function(){return fsa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.xp=function(){if(this.A){var a=g.eK(this.player).getVideoContentRect(!0);g.th(this.A.element,a.width,a.height);g.jh(this.A.element,a.left,a.top)}if(this.o){var b=g.qK(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.mM=function(a){this.zc(a.state);g.X(a.state,2)&&(this.Jl()&&this.Iy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Qs(!1))};
g.h.load=function(){g.MK.prototype.load.call(this);this.zc(g.hK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.aL,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.rp()&&(c=jsa(this,c));c={format:"XML",md:c,onError:d,fe:{}};a.isPharma&&(c.fe.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().F.get(b))&&ksa(c,b);b=b&&(b.Gn||b.Fn);if(!a.pn||b)a.he?gsa(this,a.he,c):(this.w=(0,g.x)(this.XG,this,c),this.player.addEventListener("videodatachange",this.w));g.zK(this.player,this.A.element,4);this.xp();(b=g.zB(a))&&psa(this,b);(b=g.AB(a))&&b.featuredChannel&&qsa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.zc=function(a){a=!a.isCued()&&!g.X(a,1024);g.cu(this.u,a);g.cu(this.A,a)};
g.h.XG=function(a){var b=this.player.getVideoData();b.he&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),gsa(this,b.he,a))};
g.h.unload=function(){g.NP(this.player.app,"annotations_module",void 0);g.A.forEach(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,F2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.MK.prototype.unload.call(this);g.$t(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.aL=function(a,b,c){this.C=null;!isa(this,b,a)&&(a=g.Up(c)&&c.responseXML?c.responseXML:null)&&(A3(this,a),g.K(g.fK(this.player),"iv-module-loaded"))};
g.h.bB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?lsa(this):this.load())};
g.h.Jl=function(){return!!this.o&&this.o.isAvailable()};
g.h.Iy=function(){this.Jl();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Jl();this.o&&(a?c?n3(this.o,c,b):n3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):o3(this.o))};
g.h.Qs=function(a,b){this.player.P(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.O().F.unsubscribe("vast_info_card_add",this.bB,this);g.pn(g.fK(this.player),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.sp(a[b]);this.M.length=0;g.MK.prototype.X.call(this)};g.aL.annotations_module=z3;g.aL.creatorendscreen=S2;})(_yt_player);
