(function(g){var window=this;var F3=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.rz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.F,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},G3=function(a){return a.o?a.o.languageCode:a.u},usa=function(a,b){var c=new g.qz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},vsa=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];
if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var k=a[c++],l=a[c++];e=((e&7)<<18|(f&63)<<12|(k&63)<<6|l&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],k=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|k&63)}return b.join("")},wsa=function(){this.u=[];
this.o=[]},H3=function(a,b){return b?a.o.concat(a.u):a.o},I3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Za(c,(0,g.x)(b.qb,b))||c.push(b);break;default:c=a.o,g.Za(c,(0,g.x)(b.qb,b))||c.push(b)}},J3=function(){g.B.call(this);
this.u=new wsa;this.B=[]},K3=function(a,b,c){J3.call(this,a);
this.o=null;this.B=b.mw;this.w=c},L3=function(){this.segments=[]},M3=function(a,b,c,d,e,f){g.B.call(this);
this.J=a;this.w=b;this.V=b.O();this.B=new L3;this.o=null;this.F=d;this.M=f;this.u=this.A=null;this.R=c;this.C=e||!1;this.G=new g.I(this.yy,1E3,this);g.C(this,this.G);this.H=new g.P(this);g.C(this,this.H);this.H.L(b,"SEEK_COMPLETE",this.qz);this.qz();this.yy()},xsa=function(a,b){b-=a.w.Cb();
var c=a.o;a.o=g.Xa(a.R.kg(b).o);c!=a.o&&a.M&&a.M()},ysa=function(a,b){var c=g.Dw(b,a.J,{}).Vb(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Eq(c,d,3,100).then((0,g.x)(a.JM,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.qb(c.segments,d);0<=e||0>e&&1===(-e-1)%2||(e=-e-1,0<e&&1===d-c.segments[e-1]&&e<c.segments.length&&1===c.segments[e]-d?(g.eb(c.segments,e),g.eb(c.segments,e-1)):0<e&&1===d-c.segments[e-1]?c.segments[e-1]=d:e<c.segments.length&&1===c.segments[e]-d?c.segments[e]=d:(g.nb(c.segments,e,0,d),g.nb(c.segments,e+1,0,d)))},N3=function(a,b){J3.call(this,b.O());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.Zy(this.F.O())&&!this.o.u},zsa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.NK(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.qz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Asa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},Bsa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.NK(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},O3=function(a,b,c,d,e){J3.call(this,e||null);
c=c||g.Ip(a).hl||"";c=c.split("_").join("-");this.A=g.Kp(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},P3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.TC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.u=f;this.o=k},Q3=function(a,b,c,d,e){g.TC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Csa=function(a){a=void 0===a?{}:a;
var b="_"+R3++;return new Q3(0,0x8000000000000,0,b,a)},S3=function(a,b,c,d,e,f,k){var l={};
g.Ta(l,b);g.Ta(l,a.params);g.Ta(l,c);var m={};g.Ta(m,b.Ab);a.params.Ab&&g.Ta(m,a.params.Ab);g.Ta(m,c.Ab);l.Ab=m;g.S.call(this,{D:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==l.Xc?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.R=!1;this.w=a;this.Z=this.T=null;this.Na=e;this.Ja=f;this.Ha=k;this.F=null;this.ca=.96*e;this.xa=.96*f;this.u=l;this.Ga=c;this.B=this.o["captions-text"];
this.Aa=null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.ha=this.aa*Dsa(m);a=new g.gr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.tI,this);a.subscribe("dragmove",this.sI,this);a.subscribe("dragend",this.rI,this);this.sa=this.na=0;b="";this.u.windowOpacity&&(a=g.L1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":
"","text-align":Esa[this.u.textAlign]};this.Aa&&(a["border-radius"]=b?this.ha/8+"px":"");if(this.A=2==this.w.params.Xc||3==this.w.params.Xc)b=this.element,c="vertical-rl",1==this.u.Hu&&(c="vertical-lr"),g.Od&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.bh(b,"-o-writing-mode",c),g.bh(b,"-webkit-writing-mode",c),g.bh(b,"writing-mode",c),g.bh(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.w.params.Xc&&(g.bh(b,"text-orientation",""),g.bh(b,"transform","rotate(180deg)"));g.bh(this.element,
a);switch(this.u.Vf){case 0:case 1:case 2:g.K(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},Dsa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Fsa=function(a,b){var c={},d=b.background?b.background:a.u.Ab.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Ab.backgroundOpacity;d=g.L1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ha/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*Dsa(b)+"px";d=1;e=b.color||a.u.Ab.color;if(b.color||null!=b.textOpacity)e=g.L1(e),d=null==b.textOpacity?a.u.Ab.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.br&&(k=e=b.br);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Nk()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Ab.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.We&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.ZF&&(c.visibility="hidden");1==b.Sx&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.az||g.bz,3==a.w.params.Xc?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.gf||2==b.gf||3==b.gf||4==b.gf||5==b.gf)if(g.az)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.gf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Gsa=function(a){a.F=g.Vd("SPAN");
g.bh(a.F,{display:"block"});g.K(a.F,"caption-visual-line");a.B.appendChild(a.F)},Hsa=function(a,b){var c=g.Vd("SPAN");
g.bh(c,{display:"inline-block","white-space":"pre-wrap"});g.bh(c,Fsa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.bh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.bh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Isa=function(a,b,c){a.R=a.R||!!c;
var d={};g.Ta(d,a.u.Ab);g.Ta(d,c||b.o);g.Ta(d,a.Ga.Ab);(c=!a.F)&&Gsa(a);for(var e=a.T&&a.Z&&g.A.qb(d,a.Z)?a.T:Hsa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.u,n=k[l];m&&!c?(Gsa(a),e=Hsa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Xd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.az||!g.fh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.fh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.Qd?g.bh(e,m,"1em"):g.bh(e,m,"0.5em")))}a.Z=d;a.T=e;a.C.push(b)},Jsa=function(){},U3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new T3(this);this.C=new T3(this);this.o=[];this.clear()},Lsa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{sn:a,
tn:b,result:0};a=Ksa[a];b=Ksa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{sn:a,tn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{sn:a,tn:b,result:2};return{sn:a,tn:b,result:3}},Nsa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Msa(a.B,b,c,d))},Osa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Nsa(a,d.ow,d.pw,b):1==d.type&&a.w&496&&Msa(a.C,d.ow,d.pw,b)}a.o.length=0},V3=function(){this.o=0},W3=function(){this.u=this.w=this.o=0},X3=function(){this.timestamp=this.xe=0},Y3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new X3}this.o=this.u=this.row=0;this.style=new V3;this.B=a;this.A=0},Z3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.w[m][p];
if(0!=t.xe){0==c&&(c=m,d=p);n=String.fromCharCode(t.xe);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.xe||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.w[k][m],t=p.xe,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Tsa=function(a,b){switch(a){case 0:return Psa[(b&127)-32];
case 1:return Qsa[b&15];case 2:return Rsa[b&31];case 3:return Ssa[b&31]}return 0},$3=function(a){return a.w[a.row][a.u]},a4=function(a,b,c){2<=b&&1<a.u&&(--a.u,$3(a).xe=0);
var d=$3(a);d.timestamp=a.B.u+0;d.xe=Tsa(b,c);32>a.u&&a.u++},Usa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].bi(a.w[c+e][f])},b4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},c4=function(a){a.row=0<a.o?a.o:1;
a.u=1;b4(a,0,15)},d4=function(a){this.A=a;
this.B=0;this.style=new V3;this.C=new Y3(a);this.F=new Y3(a);this.G=new Y3(a);this.u=this.C;this.w=this.F;this.o=this.u},e4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:Z3(d,c),c4(a.u),c4(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(Z3(d,c),b4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},Vsa=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},Wsa=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},T3=function(a){this.u=a;
this.o=new W3;this.B=0;this.w=new d4(a);this.C=new d4(a);this.A=this.w},Msa=function(a,b,c,d){a.o.update();
b=Lsa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.sn;c=b.tn;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&a4(a,0,b),c&96&&a4(a,0,c),0!=b&&0!=c&&3==a.style.o&&Z3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Usa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));b4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:a4(b.o,0,32);break a;case 48:57==c?(d=b.o,$3(d).xe=0,32>d.u&&d.u++):a4(b.o,1,c&15)}break;case 2:c&32&&a4(b.o,2,c&31);break;case 3:c&32&&a4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Vsa(b);break;
case 33:d=b.o;1<d.u&&(--d.u,$3(d).xe=0);break;case 36:d=b.o;b=$3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:e4(b,2,d);break;case 38:e4(b,3,d);break;case 39:e4(b,4,d);break;case 40:a4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);c4(d);Wsa(b);break;case 43:Wsa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:Z3(a,d)}b4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;Z3(a,d);Usa(a,b,b+1,a.o-1);b4(a,a.row,1)}break;case 46:b4(b.w,0,15);break;case 47:Z3(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,Vsa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},Ysa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Nb){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=Xsa(l.textContent,n.textContent,p.textContent,f.textContent,k);return new P3(a,b,e,c,l,d,m)}switch(m.Nb){case 9:case 10:m.gf=1;break;case 11:m.gf=2;break;case 12:m.gf=3;break;case 13:m.gf=4;break;case 14:m.gf=5}return new P3(a,b,e,c,l.textContent||"",d,m)},Xsa=function(a,b,c,d,e){var f=g.Nk(),k=f?
g.Vd("DIV"):g.Vd("RUBY"),l=g.Vd("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.Vd("DIV"):g.Vd("RP");a.textContent=b;k.appendChild(a);b=f?g.Vd("DIV"):g.Vd("RT");b.textContent=c;k.appendChild(b);c=e.Nb;if(10==c||11==c||12==c||13==c||14==c)if(g.bh(b,"text-emphasis-style","filled circle"),g.bh(b,"text-emphasis-color","currentcolor"),g.bh(b,"webkit-text-emphasis","filled circle"),e.Nb==e.Nb==11||13==e.Nb)g.bh(b,"webkit-text-emphasis-position","under left"),g.bh(b,"text-emphasis-position","under left");c=!0;if(4==e.Nb||7==e.Nb||12==e.Nb||14==
e.Nb)g.bh(k,"ruby-position","over"),g.bh(k,"-webkit-ruby-position","before");else if(5==e.Nb||6==e.Nb||11==e.Nb||13==e.Nb)g.bh(k,"ruby-position","under"),g.bh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.Vd("DIV"):g.Vd("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.bh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.bh(f,"display","none"),f=f.nextElementSibling,g.bh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.bh(k.lastElementChild,"display","none"),d?(g.bh(k,"padding-top","0.6em"),g.bh(f,"top","0")):(g.bh(k,"padding-bottom","0.6em"),g.bh(f,"bottom","0")));return k},f4=function(){g.B.apply(this,arguments)},g4=function(a){f4.call(this);
this.A={};this.H={};this.J={};this.B="_"+R3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},h4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},i4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},j4=function(a,b){var c=h4(a,b);
return void 0!=c?c:null},l4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return k4.test(c),c},Zsa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.J[d]:a.C);d=j4(b,"mh");null!=d&&(c.Kj=d);d=j4(b,"ju");null!=d&&(c.textAlign=d);d=j4(b,"pd");null!=d&&(c.Xc=d);d=j4(b,"sd");null!=d&&(c.Hu=d);d=l4(b,"wfc");null!=d&&(c.windowColor=d);d=h4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},$sa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.H[d]);d=j4(b,"ap");null!=d&&(c.Vf=d);d=h4(b,"cc");null!=d&&(c.Vg=d);d=h4(b,"ah");null!=d&&(c.Ye=d);d=h4(b,"rc");null!=d&&(c.Fg=d);d=h4(b,"av");null!=d&&(c.Hg=d);return c},ata=function(a,b,c,d){var e={};
g.Ta(e,$sa(a,b));g.Ta(e,Zsa(a,b));d?g.A.qb(e,a.C)?(d=a.B,e=a.C):d="_"+R3++:d=b.getAttribute("id")||"_"+R3++;a=h4(b,"t")+c;b=h4(b,"d")||0x8000000000000;if(2==e.Xc||3==e.Xc)c=e.Fg,e.Fg=e.Vg,e.Vg=c;return new Q3(a,b,0,d,e)},m4=function(a){f4.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},n4=function(a){a=g.td(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},bta=function(a,b,c,d,e){0==d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.Fg=a);b=b.ccColCount;void 0!=b&&(f.Vg=b);if(2===f.Xc||3===f.Xc)b=f.Fg,f.Fg=f.Vg,f.Vg=b;return new Q3(c,d,0,e,f)},o4=function(a,b,c,d,e,f,k){S3.call(this,a,b,c,d,e,f,k);
this.type=1},p4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},q4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},r4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},s4=function(a,b){f4.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new U3;this.o.w=1<<this.track},t4=function(a){if("string"===typeof a)return!1;
a=new p4(a,8,0);return cta(a)},cta=function(a){if(!(a.o<a.u.byteLength)||1380139777!=r4(a))return!1;
a.version=q4(a);if(1<a.version)return!1;q4(a);q4(a);q4(a);return!0},u4=function(a,b,c,d,e,f,k){S3.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.H=this.da=0;this.M=NaN;this.ya=0;this.Ba=null;this.ea=new g.I(this.PM,433,this);g.C(this,this.ea);g.bh(this.element,"overflow","hidden")},dta=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},eta=function(a){if(isNaN(a.M)){var b=a.u.Vg;
if(b){var c=g.Vd("SPAN");g.ee(c,"\u2013".repeat(b));g.bh(c,Fsa(a,a.u.Ab));a.B.appendChild(c);a.M=c.offsetWidth;a.B.removeChild(c)}else a.M=0}return a.M},fta=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.Hu&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},gta=function(a){a.G=[].concat(g.na(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.Fg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.J=Math.max(eta(a),a.ya,dta(a,a.B))},hta=function(a,b){gta(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.dn(a.ea));g.bh(a.B,"transform",fta(a,c));a.da=c}gta(a)},v4=function(){f4.call(this)},ita=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.We=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new P3(b,c,d,e.id,p.nodeValue,f||0<n,g.A.isEmpty(l)?void 0:l),m.push(p),e.o.push(p);else{var t={};g.Ta(t,l);ita(a,b,c,d,e,!0,p,t,m)}}},w4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},jta=function(a,b,c,d){d=Object.assign({Kj:0},d);
return new Q3(a,b,c,"_"+R3++,d)},x4=function(a){g.B.call(this);
this.u=a;this.o=null},lta=function(a){var b={};
if(a=G3(a))b.lang=a,kta.test(a)&&(b.Xc=1);return b},A4=function(a){g.MK.call(this,a);
this.w=a.O();this.S=a.getVideoData();this.ya=g.eK(a);this.T=a;var b=null,c=g.Un("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Dn(c));this.ca=b;this.A={Ab:{}};this.C={Ab:{}};this.J=[];this.V={};this.aa={};this.M=!1;this.sa=g.OK(this.S,this.T);this.Aa=!!this.S.captionTracks.length;this.Ba=!!this.S.Gk;this.ha="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.Im());this.xa=!(!b||!b.Wi());this.B=this.ha&&c&&!this.sa;this.H=!this.B&&this.ha&&this.xa&&this.sa;this.u=this.F=this.G=this.Z=this.ra=
null;this.da=new x4(this.w);g.C(this,this.da);c=b=this.o=null;this.B||(b=new g.$m(this.CC,void 0,this),g.C(this,b),c=new g.I(this.oO,2E3,this),g.C(this,c));this.ea=b;this.na=c;this.R=new g.P(this);g.C(this,this.R);this.B||this.R.L(a,"resize",this.Su);this.R.L(a,"onPlaybackAudioChange",this.sK);this.R.L(a,g.WC("captions"),this.fH,this);this.R.L(a,"crx_captions",this.gH,this);y4(this,z4(this,"display-settings")||{})},B4=function(a){if(1==a.w.Ug||1==a.S.Ug||"alwayson"==g.rB(a.S,"yt:cc"))return!0;
if(2==a.w.Ug){var b=z4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().Yq;return"ON"==c||"on"==g.rB(a.S,"yt:cc")},C4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Xn||"FORCED_ON"==c.Yq},E4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ba?!1:a.Aa?!1:!0);c=H3(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.rB(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(G3(c[f])==d[e])return c[f];return a.F&&a.F.kr?a.F.kr:(d=c.find(function(k){return k.isDefault}))?d:c[0]||D4(a)}return null},D4=function(a){return a.F&&a.F.Xn},F4=function(a){var b=D4(a);
return!!b&&a.o==b},mta=function(a,b){for(var c=a.T.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},H4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&G4(a,"module-enabled",!!b));a.o=b;C4(a)&&(a.o=D4(a));a.load()},nta=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.u:null;!b.params.Xc&&d&&kta.test(d)&&(b.params.Xc=1);d=a.ya.getPlayerSize();switch(null!=b.params.Kj?b.params.Kj:1<b.o.length?1:0){case 1:return new o4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new u4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new S3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},y4=function(a,b,c){c=void 0===c?!1:c;
var d=I4.Ab;a.A={};g.Ta(a.A,I4);a.A.Ab={};g.Ta(a.A.Ab,d);a.C={Ab:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;k4.test(f);e.Ab.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;k4.test(f);e.Ab.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||I4.windowColor;k4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ab.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Ab.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.We?3:d.bold?1:d.We?2:0);f=f.Ab;switch(e){case 1:f.bold=!0;delete f.We;break;case 2:delete f.bold;f.We=!0;break;case 3:f.bold=!0;f.We=!0;break;default:delete f.bold,delete f.We}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ab.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=I4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.A;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ab.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ab.fontFamily=f;a.loaded&&a.Su();c&&G4(a,"display-settings",b)},pta=function(a,b){if(b&&!a.G){var c=Csa({Xc:0,
lang:"en"});a.G=[c,new P3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.vK(a.player,a.G)}else!b&&a.G&&(ota(a,a.G),a.G=null)},ota=function(a,b){g.IS(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.fb(this.J,c)},a);
g.an(a.ea)},z4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},G4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.ju.prototype.mo=g.ca(10,function(a){return(a=this.gg(a))?a.o:0});
g.Vw.prototype.mo=g.ca(9,function(){return 0});
g.Dt.prototype.Hk=g.ca(8,function(){for(var a=g.Hd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ae(a[b])});
g.nQ.prototype.Hk=g.ca(7,function(){this.o.Hk()});
g.Dt.prototype.Im=g.ca(6,function(){return!!this.o.textTracks});
g.nQ.prototype.Im=g.ca(5,function(){return this.o.Im()});
g.Dt.prototype.Ck=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.nQ.prototype.Ck=g.ca(3,function(a){this.o.Ck(a)});
g.tt.prototype.Wi=g.ca(2,function(){});
g.Dt.prototype.Wi=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.nQ.prototype.Wi=g.ca(0,function(){return this.o.Wi()});
var kta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,k4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(J3,g.B);J3.prototype.pB=function(){return!1};
J3.prototype.X=function(){this.Kh();g.B.prototype.X.call(this)};
g.r(K3,J3);K3.prototype.Ms=function(a,b,c){this.ga();b=this.fl(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Kh();this.o=g.$p(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
K3.prototype.Ns=function(a){if(this.w)for(var b=g.q(this.w.captionTracks),c=b.next();!c.done;c=b.next())I3(this.u,c.value);a()};
K3.prototype.fl=function(a,b){var c=a.Vb(),d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.Nk()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=G3(a));return g.Kp(c,d)};
K3.prototype.Kh=function(){this.o&&this.o.abort()};
L3.prototype.contains=function(a){a=g.qb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
L3.prototype.length=function(){return this.segments.length/2};
g.r(M3,g.B);g.h=M3.prototype;g.h.X=function(){g.B.prototype.X.call(this);this.u&&this.u.cancel()};
g.h.qz=function(){xsa(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new L3;this.u&&(this.u.cancel(),this.u=null)};
g.h.yy=function(){this.ga();var a;if(a=null!==this.o)a=this.o,a=a.o.yg(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.Oj(a),a.o[0].duration?(this.B.contains(a.o[0].u)||ysa(this,a),this.o=g.Xa(a.o)):!g.T(this.V.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.Cb()<this.w.getCurrentTime()&&xsa(this,this.w.getCurrentTime()));this.G.start()};
g.h.JM=function(a){this.ga();var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.$w(a);c?(a=g.Dw(this.A,this.J,{}),b=this.A,g.zw(b.u,a,c),b.requestId=a.get("req_id"),ysa(this,this.A)):(b||null===this.F||(c=this.A.o[0],this.C?this.F(a.response,1E3*(c.startTime+this.w.Cb())):this.F(a.responseText,1E3*(c.startTime+this.w.Cb()))),this.u=this.A=null)};
g.r(N3,J3);g.h=N3.prototype;g.h.Ms=function(a,b,c){this.Kh();b=Asa(this,a.getId());b||(b=a.u,b=this.o.u?Bsa(this,b,"386"):Bsa(this,b));if(b){var d=1E3*(b.index.mo(b.index.Ue())-b.index.kd(b.index.Ue()));this.w=new M3(new g.Wv,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.xs(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.pB=function(){var a=this.A;this.A=!1;return a};
g.h.Ns=function(a){var b;this.C?b=[new g.qz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.qz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?zsa(this,"386"):zsa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())I3(this.u,c.value);a()};
g.h.Kh=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.fl=function(){return""};
g.r(O3,J3);O3.prototype.Ms=function(a,b,c){this.ga();b=this.fl(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Kh();this.o=g.$p(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
O3.prototype.Ns=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.Kp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
I3(this.u,new g.qz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Kh();this.o=g.$p(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
O3.prototype.fl=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=G3(a));return c=g.Kp(c,d)};
O3.prototype.Kh=function(){this.o&&this.o.abort()};var Esa=["left","right","center","justify"];var I4={windowColor:"#080808",windowOpacity:0,textAlign:2,Vf:7,Ye:50,Hg:100,Ab:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(P3,g.TC);P3.prototype.toString=function(){return g.TC.prototype.toString.call(this)};g.r(Q3,g.TC);Q3.prototype.toString=function(){return g.TC.prototype.toString.call(this)};
var R3=0;g.r(S3,g.S);g.h=S3.prototype;g.h.tI=function(a,b){var c=g.rh(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.sI=function(a,b){var c=g.uh(this.element),d=a-this.na-.02*this.Na,e=b-this.sa-.02*this.Ja,f=(d+c.width/2)/this.ca*3;f=Math.floor(g.td(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.td(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ca;d=100*g.td(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.td(c,0,1);this.w.params.Vf=l;this.w.params.Hg=c;this.w.params.Ye=d;this.u.Vf=l;this.u.Hg=c;this.u.Ye=d;this.PB()};
g.h.rI=function(){g.pn(this.element,"ytp-dragging")};
g.h.PB=function(){this.Si(this.C)};
g.h.Si=function(a){var b=Math.min(this.nx(),this.ca),c=this.mx(),d="";3==this.w.params.Xc&&(d="rotate(180deg)");g.bh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Qq(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Ye+2;d=this.u.Vf;switch(d){case 0:case 3:case 6:b=this.u.Ab.fontSizeIncrement;!g.T(this.Ha,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!=this.u.Xc&&3!=this.u.Xc&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Hg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.bh(this.element,a)};
g.h.Qq=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.R||this.C.length>b)b=0,this.R=!1,this.C=[],this.F=this.Z=this.T=null,g.Zd(this.B);for(;b<a.length;b++)Isa(this,a[b])};
g.h.nx=function(){return 0};
g.h.mx=function(){return 0};
g.h.toString=function(){return g.S.prototype.toString.call(this)};Jsa.prototype.B=function(){};U3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
U3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Ksa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];V3.prototype.set=function(a){this.o=a};
V3.prototype.get=function(){return this.o};
W3.prototype.clear=function(){this.o=0};
W3.prototype.update=function(){this.o=2==this.o?1:0};
W3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
X3.prototype.bi=function(a){this.xe=a.xe;this.timestamp=a.timestamp};
X3.prototype.reset=function(){this.timestamp=this.xe=0};
Y3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
Y3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.xe?a+"_":a+String.fromCharCode(d.xe)}a+="\n"}return a};
Y3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Psa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Qsa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Rsa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Ssa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];d4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
T3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(f4,g.B);f4.prototype.w=function(){return[]};
f4.prototype.reset=function(){};g.r(g4,f4);g4.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
g4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ta(l,this.A[m]);m=i4(c,"b");null!=m&&(l.bold=
m);m=i4(c,"i");null!=m&&(l.We=m);m=i4(c,"u");null!=m&&(l.underline=m);m=j4(c,"et");null!=m&&(l.charEdgeStyle=m);m=j4(c,"of");null!=m&&(l.offset=m);m=l4(c,"bc");null!=m&&(l.background=m);m=l4(c,"ec");null!=m&&(l.br=m);m=l4(c,"fc");null!=m&&(l.color=m);m=j4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=h4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=h4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=h4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=j4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Nb=10<m?m-1:m);
c=j4(c,"hg");null!=c&&(l.Sx=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=Zsa(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=$sa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=ata(this,d,e,!1);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!i4(d,"a");n=
(h4(d,"t")||0)+n;var p=h4(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.na(d.childNodes));z.length&&(this.F=null!=d.getAttribute("d"));for(var D=0;D<z.length;D++){var E=z[D],F=void 0;0<D&&(m=!0);var G=void 0;1==E.nodeType&&(G=E);if(G&&"s"==G.tagName){if((E=this.A[G.getAttribute("p")])&&E.Nb&&(1==E.Nb?(E=z.slice(D,D+4),4==E.length&&(F=Ysa(n,p,l,m,t,E,this.A),D+=3)):
F=Ysa(n,p,l,m,t,[G],this.A)),!F){var J=G;F=n;G=p;E=l;var ma=m,ta=t,rc=J.textContent?J.textContent:"",Wd=this.A[J.getAttribute("p")];J=h4(J,"t")||0;F=new P3(F+J,G-J,ta,E,rc,ma,Wd)}}else F=new P3(n,p,t,l,E.textContent||"",m,u);k.push(F);this.u=F}if(0<k.length)for(k[0].windowId==this.B&&(this.o=ata(this,d,e,!0),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var qta=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(m4,f4);m4.prototype.reset=function(){this.u.clear()};
m4.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.We=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!=f.ecEdgeColor&&(k.br=n4(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!=
f.fcForeColor&&(k.color=n4(f.fcForeColor));void 0!=f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!=f.bcBackColor&&(k.background=n4(f.bcBackColor));void 0!=f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Nb=10<l?l-1:l,k.gf=qta.get(k.Nb));f.hgHorizGroup&&(k.Sx=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=
f.mhModeHint&&(k.Kj=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Xc=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.Hu=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=n4(f.wfcWinFillColor)),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.Ye=f.ahHorPos),
void 0!=f.apPoint&&(l.Vf=f.apPoint),void 0!=f.avVerPos&&(l.Hg=f.avVerPos),void 0!=f.ccCols&&(l.Vg=f.ccCols),void 0!=f.rcRows&&(l.Fg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=bta(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+R3++,l=bta(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,p=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],D=z.utf8;if(D){var E=z.tOffsetMs||0,F=null;z.pPenId&&(F=this.o.get(z.pPenId));if(2===(null!=l.params.Kj?l.params.Kj:1<l.o.length?1:0)&&n&&"\n"===D)continue;if(z=F&&1===F.Nb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var G=t[z+1].pPenId;(G=this.o.get(G))&&G.Nb&&2==G.Nb?(G=t[z+2].pPenId,G=this.o.get(G),!G||!G.Nb||3>G.Nb?z=!1:(G=t[z+3].pPenId,z=(G=this.o.get(G))&&G.Nb&&2==G.Nb?!0:
!1)):z=!1}if(z){E=t[m+1].utf8;z=t[m+3].utf8;G=t[m+2].utf8;var J=this.o.get(t[m+2].pPenId);D=Xsa(D,E,G,z,J);n=new P3(e,f,p,k,D,n,F);m+=3}else n=new P3(e+E,f-E,p,l.id,D,n,F||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};g.r(o4,S3);o4.prototype.Qq=function(a){var b=this.w.o;S3.prototype.Qq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,rta);var e=c.o;var f=d}Isa(this,c,d)}};
var rta={ZF:!0};g.r(p4,Jsa);p4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+R3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new Q3(c,d-c,5,f,{textAlign:0,Vf:0,Ye:2.5*b,Hg:5.33*a});e=new P3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(s4,f4);s4.prototype.w=function(a){a=new p4(a,a.byteLength,this.u);if(cta(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=r4(a)*(1E3/45):1==a.version&&(a.A=4294967296*r4(a)+r4(a)),a.C=q4(a);0<a.C;a.C--){var b=q4(a),c=q4(a),d=q4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,ow:c,pw:d,order:b.o.length}))}Osa(this.o,a);return a.w}return[]};
s4.prototype.reset=function(){this.o.clear()};g.r(u4,S3);g.h=u4.prototype;g.h.PB=function(){g.en(this.ea)};
g.h.PM=function(){g.pn(this.element,"ytp-rollup-mode");this.Si(this.Ba,!0)};
g.h.mx=function(){return this.A?this.J:this.H};
g.h.nx=function(){return this.A?this.H:this.J};
g.h.Si=function(a,b){this.Ba=a;if(this.w.params.Fg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.J;this.H=this.J=0;S3.prototype.Si.call(this,a);hta(this,b);S3.prototype.Si.call(this,a)}else S3.prototype.Si.call(this,a)};g.r(v4,f4);
v4.prototype.w=function(a,b){for(var c=[],d=a.split(sta),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!tta.test(f)){var l=J4.exec(f);if(l&&4<=l.length){var m=w4(l[1]),n=w4(l[2])-m;m+=k;var p,t=p=void 0,u=void 0,z=void 0,D=(l=l[3])?l.split(" "):[];l={textAlign:2};D=g.q(D);for(var E=D.next();!E.done;E=D.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.Hg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
t=E[0];l.Ye=Number.parseInt(t,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Hg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Ye=0;break;case 1:l.Ye=100;break;default:l.Ye=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Vf=0>t||8<t?7:t;p=l;f=f.substring(J4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=jta(m,n,5,t),n=new P3(m,n,5,k.id,p,!1,g.A.isEmpty(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=p.split(uta),1==u.length?(p=5,t=jta(m,n,p,t)):(z=p=6,t=Object.assign({Vg:32},t),t=new Q3(m,n,z,"_"+R3++,t)),c.push(t),z=m,l=0;l<u.length;l++)D=u[l],0==l%2?(E=g.M1("<html>"+D+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(D))):F=E.firstChild,ita(this,z,n-(z-m),p,t,0<l,F,f,c)):z=w4(D)+k}J4.lastIndex=0}}return c};
var tta=/^NOTE/,sta=/(?:\r\n|\r|\n){2,}/,J4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),uta=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(x4,g.B);x4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
x4.prototype.reset=function(){this.o&&this.o.reset()};
x4.prototype.X=function(){this.clear();g.B.prototype.X.call(this)};g.r(A4,g.MK);g.h=A4.prototype;g.h.X=function(){if(this.B||this.H){var a=this.T.app.B;a&&!a.ga()&&a.Hk()}else pta(this,!1);g.MK.prototype.X.call(this)};
g.h.load=function(){g.MK.prototype.load.call(this);var a=!g.T(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?mta(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Ms(this.o,"json3",(0,g.x)(this.yN,this)),!a||this.B||this.H||F4(this)||this.player.ma("captionschanged",F3(this.o))),a||(this.o&&!F4(this)?this.player.ma("captionschanged",F3(this.o)):this.player.ma("onCaptionsTrackListChanged"));
else{var b;this.sa?b=new N3(this.S.la,this.player):this.Aa?b=new K3(this.w,this.S,this.player.getAudioTrack()):b=new O3(this.S.Gk,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.rB(this.S,"yt:cc_default_lang")||this.w.lc,this.S.Wq,this.w);this.u=b;g.C(this,this.u);b.Ns((0,g.x)(this.xN,this))}};
g.h.unload=function(){this.B&&this.o?mta(this,!1):(this.na&&g.fn(this.na),g.NP(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Kh(),this.da.clear(),this.G&&g.vK(this.player,this.G),this.Su());g.MK.prototype.unload.call(this);var a=g.R(this.player.app);a&&g.tH(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ha?this.B||this.H:C4(this)||B4(this))&&this.load()};
g.h.xN=function(){var a;this.M||B4(this)?a=E4(this,this.M):C4(this)&&(a=D4(this));if(this.B||this.H){for(var b=H3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.rz(e),srclang:G3(e),id:e.toString()};this.H||(f.src=this.u.fl(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Ud("TRACK",f))}a=this.T.app.B;a.Ck(c);c=a.Za();this.xa&&this.R.L(c.textTracks,"change",this.zN)}else!this.o&&a&&H4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.zN=function(){for(var a=this.T.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=H3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&H4(this,b,!0)};
g.h.cP=function(){!this.o&&this.B||this.unload()};
g.h.yN=function(a,b,c,d){if(a){this.u.pB()&&(this.J=[],g.NP(this.T.app,"captions",void 0),g.an(this.ea),this.da.reset());var e=this.da;c=c||0;d=d||0;if(e.u.fa("html5_disable_rawcc_killswitch")){if("string"!==typeof a){var f=new DataView(a);8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Au(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),t4(a)||(a=vsa(new Uint8Array(a))))}}else"string"===typeof a||t4(a)||(f=new DataView(a),a=8>=f.byteLength||1718909296!==f.getUint32(4)?"":(f=g.Au(f,0,
1835295092))&&f.size?vsa(new Uint8Array(a.slice(f.dataOffset,f.dataOffset+f.size))):"");if(a)try{if("string"!==typeof a){var k=a,l=c,m=d;if(!t4(k))throw Error("Invalid binary caption track data");e.o||(e.o=new s4(m,b));var n=e.o.w(k,l)}else{if("WEBVTT"==a.substring(0,6))b=a,m=c,e.o||(e.o=new v4),l=e.o.w(b,m),.01>Math.random()&&g.po(Error("Deprecated subtitles format in web player: WebVTT")),k=l;else b:{l=a;if("{"===l[0])try{e.o||(e.o=new m4(lta(b)));k=e.o.w(l,c);break b}catch(E){g.N(E);k=[];break b}m=
g.M1(l);if(!m||!m.firstChild){var p=Error("Invalid caption track data");p.params=l;throw p;}if("timedtext"==m.firstChild.tagName){if(3==parseInt(m.firstChild.getAttribute("format"),10)){e.o||(e.o=new g4(lta(b),e.u));k=e.o.w(m,c);break b}var t=Error("Unsupported subtitles format in web player (Format2)");t.params=l;throw t;}if("transcript"==m.firstChild.tagName){var u=Error("Unsupported subtitles format in web player (Format1)");u.params=l;throw u;}var z=Error("Invalid caption track data");z.params=
l;throw z;}n=k}var D=n}catch(E){g.N(E),e.clear(),D=[]}else D=[];g.vK(this.player,D);!this.M||this.H||F4(this)||g.Oy(this.w)||g.Py(this.w)||(g.fn(this.na),D=Csa({Vf:0,Ye:5,Hg:5,Fg:2,textAlign:0,Xc:0,lang:"en"}),this.Z=[D],e=["Click "," for settings"],this.ra||(n=new g.Zt(g.FL()),g.C(this,n),this.ra=n.element),n=D.end-D.start,(b=g.rz(this.o))&&this.Z.push(new P3(D.start,n,0,D.id,b)),this.Z.push(new P3(D.start,n,0,D.id,e[0]),new P3(D.start,n,0,D.id,this.ra,!0),new P3(D.start,n,0,D.id,e[1],!0)),g.vK(this.player,
this.Z),g.dn(this.na));!this.M||this.H||F4(this)||(G4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(D=g.R(this.player.app))&&g.tH(D.B));this.M=!1}};
g.h.fH=function(a){this.J.push(a);g.an(this.ea)};
g.h.gH=function(a){g.fb(this.J,a);this.u instanceof N3&&this.u.C&&g.IS(this.player.app,[a],void 0);g.an(this.ea)};
g.h.gO=function(a){if(a instanceof Q3){var b=this.V[a.id];b&&b.w!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=nta(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.oO=function(){ota(this,this.Z);this.Z=null};
g.h.CC=function(){this.ea.stop();g.A.clear(this.aa);this.J.sort(g.VC);var a=this.J;if(this.G){var b=(0,g.be)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.gO,this);g.A.forEach(this.V,function(c,d){this.aa[d]?(c.element.parentNode||g.zK(this.player,c.element,4),c.Si(this.aa[d])):(c.dispose(),delete this.V[d])},this)};
g.h.vO=function(){y4(this,{},!0);g.T(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.nF=function(){var a=I4.Ab;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.We?3:a.bold?1:a.We?2:0,textOpacity:a.textOpacity,windowColor:I4.windowColor,windowOpacity:I4.windowOpacity};var b=z4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.IC=function(a,b){b=void 0===b?!1:b;var c={};g.Ta(c,z4(this,"display-settings"));g.Ta(c,a);y4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Su=function(){!this.B&&this.loaded&&(g.A.forEach(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.CC())};
g.h.Qc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.td(b,-2,4);this.IC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&H4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.Eb&&G4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Pa(b))break;if(g.A.isEmpty(b)){H4(this,null,!0);break}for(var d=H3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?usa(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||H4(this,c,!0)}else return this.loaded&&this.o&&!F4(this)?F3(this.o):{};return"";case "tracklist":return this.u?(0,g.ic)(H3(this.u.u,!(!b||!b.includeAsr)),function(k){return F3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||pta(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.Eb&&a.push("stickyLoading");return a};
g.h.HG=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.WO=function(){this.loaded&&this.o&&!F4(this)?(G4(this,"module-enabled",!1),this.unload(),C4(this,!0)&&H4(this,D4(this),!1)):H4(this,F4(this)||!this.o?E4(this,!0):this.o,!0)};
g.h.sK=function(){var a=F4(this);C4(this,a)?H4(this,this.player.getAudioTrack().Xn,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.ha?this.B||this.H:C4(this)||B4(this))&&(a?H4(this,E4(this),!1):this.load()))};g.aL.captions=A4;})(_yt_player);
