(function(g){var window=this;var W4=function(a,b,c){var d=b.wa();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Dc(c?c:"mqdefault.jpg");var f=b instanceof g.TA&&b.lengthSeconds?g.cL(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.XC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.TA?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Dk||g.ML("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ni(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.YC&&(d.playlist_length=b.getLength());a.update(d)},X4=function(a){g.S.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.S({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.C(this,this.B);this.B.ka("click",this.xK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.I(this.Kn,5E3,this);g.C(this,this.G);this.H=0;g.BK(this.u,this.element,this,18788);this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.hM);this.nA();this.L(a,"autonavvisibility",
this.nA);this.L(a,"mdxnowautoplaying",this.zL);this.L(a,"mdxautoplaycanceled",this.AL);this.L(a,"mdxautoplayupnext",this.HC);3==this.u.getPresentingPlayerType()&&(a=(a=g.iK(g.aK(this.u)))?a.lF():null)&&this.HC(a);g.L(this.element,"ytp-upnext-mobile",this.u.O().o)},Y4=function(a,b){if(!a.w){g.zo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.O)();a.w=new g.I((0,g.x)(a.Oq,a,b),25);a.Oq(b);var c=b||g.U(a.u.O().experiments,"autoplay_time")||1E4;a.u.ma("onAutonavCoundownStarted",c)}g.pn(a.element,"ytp-upnext-autoplay-paused")},$4=function(a){Z4(a);
a.H=(0,g.O)();a.Oq();g.K(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){a.w&&(a.w.dispose(),a.w=null)},a5=function(a,b){g.S.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Hta=function(a){a5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.S({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",N:{src:b.Nd}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.bP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Lg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},b5=function(a){var b=a.O(),c=g.Qs||g.eh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.S.call(this,{D:"a",Y:e,N:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",N:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.w=new g.P(this);g.C(this,this.w);this.ka("click",this.onClick);this.ka("keypress",this.B);this.w.L(a,"videodatachange",this.A);g.CK(a,this.element,this);this.A()},c5=function(a){a5.call(this,a,"videowall-endscreen");
var b=this;this.U=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.P(this);g.C(this,this.w);this.F=new g.I(function(){g.K(b.element,"ytp-show-tiles")},0);
g.C(this,this.F);var c=new g.S({D:"button",Y:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Previous"},K:[g.kL()]});g.C(this,c);c.ba(this.element);c.ka("click",this.xH,this);this.table=new g.Zt({D:"div",I:"ytp-endscreen-content"});g.C(this,this.table);this.table.ba(this.element);c=new g.S({D:"button",Y:["ytp-button","ytp-endscreen-next"],N:{"aria-label":"Next"},K:[g.lL()]});g.C(this,c);c.ba(this.element);c.ka("click",this.wH,this);this.u=new X4(a);g.C(this,this.u);g.zK(this.player,this.u.element,
4);this.hide()},d5=function(a){return g.AK(a.player)&&a.dw()&&!a.B},Ita=function(a,b){return(0,g.ic)(b.suggestions,function(c){c=g.nN(a.U.O(),c);
g.C(a,c);return c})},e5=function(a){var b=a.Ys();
b!==a.H&&(a.H=b,a.player.P("autonavvisibility"))},f5=function(a){g.MK.call(this,a);
this.endScreen=null;this.listeners=new g.P(this);g.C(this,this.listeners);this.o=a.O();Jta(a)?this.endScreen=new c5(this.player):this.o.Ja?this.endScreen=new Hta(this.player):this.endScreen=new a5(this.player);g.C(this,this.endScreen);g.zK(this.player,this.endScreen.element,4);this.OB();this.listeners.L(a,"videodatachange",this.OB,this);this.listeners.L(a,g.WC("endscreen"),this.uH,this);this.listeners.L(a,"crx_endscreen",this.PK,this)},Jta=function(a){a=a.O();
return a.Ha&&!a.Ja};
g.r(X4,g.S);g.h=X4.prototype;g.h.Kn=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.nA=function(){g.cu(this,g.bK(this.u));g.FK(this.u,this.element,g.bK(this.u))};
g.h.YL=function(){window.focus();this.Kn()};
g.h.hide=function(){g.S.prototype.hide.call(this)};
g.h.Oq=function(a){a=a||g.U(this.u.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.O)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?this.select(!0):this.w&&this.w.start()};
g.h.select=function(a){a=void 0===a?!1:a;if(g.T(this.u.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"==b?Notification.requestPermission():"granted"!=b||document.hasFocus()||(b=this.A.wa(),this.Kn(),this.C=new Notification("Up Next",{body:b.title,icon:b.Dc()}),this.F=this.L(this.C,"click",this.YL),this.G.start())}Z4(this);this.u.nextVideo(!1,a)};
g.h.hM=function(a){!g.de(this.B.element,g.cp(a))&&g.SL(a,this.u)&&this.select()};
g.h.xK=function(){g.dK(this.u,!0)};
g.h.zL=function(a){this.u.getPresentingPlayerType();this.show();Y4(this,a)};
g.h.HC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,W4(this,a,"hqdefault.jpg"))};
g.h.AL=function(){this.u.getPresentingPlayerType();Z4(this);this.hide()};
g.h.X=function(){Z4(this);this.Kn();g.S.prototype.X.call(this)};g.r(a5,g.S);g.h=a5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.dw=function(){return!1};
g.h.Ys=function(){return!1};
g.h.ky=function(){return!1};g.r(Hta,a5);g.r(b5,g.S);b5.prototype.select=function(){var a=this.suggestion.wa().videoId,b=this.suggestion.getPlaylistId();(g.FS(this.api.app,a,this.suggestion.Ob,b,void 0,void 0)||this.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.EK(this.api,this.element)};
b5.prototype.onClick=function(a){g.SL(a,this.api,this.u,this.suggestion.Ob||void 0)&&this.select()};
b5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
b5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.O();this.u=a.Ec?!1:b.u};g.r(c5,a5);g.h=c5.prototype;g.h.create=function(){a5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Ita(this,a),this.videoData=a);this.Dg();this.w.L(this.player,"appresize",this.Dg);this.w.L(this.player,"onVideoAreaChange",this.Dg);this.w.L(this.player,"videodatachange",this.yH);this.w.L(this.player,"autonavchange",this.Zs);this.w.L(this.player,"autonavcancel",this.vH);a=this.videoData.autonavState;a!==this.G&&this.Zs(a);this.w.L(this.element,"transitionend",this.AN)};
g.h.destroy=function(){g.cr(this.w);g.oe(this.stills);this.stills=[];this.suggestions=null;a5.prototype.destroy.call(this);g.pn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.dw=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){a5.prototype.show.call(this);g.pn(this.element,"ytp-show-tiles");this.player.O().o?g.en(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.dK(this.player,!1);d5(this)?(e5(this),2===this.videoData.autonavState?g.T(this.player.O().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):Y4(this.u):3===this.videoData.autonavState&&$4(this.u)):(g.dK(this.player,!0),e5(this))};
g.h.hide=function(){a5.prototype.hide.call(this);$4(this.u);e5(this)};
g.h.AN=function(a){g.cp(a)===this.element&&this.Dg()};
g.h.Dg=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.qK(this.U,!0,this.U.isFullscreen()),b=g.TB(this.U);b&&(b=b.uc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.td(a.width/m||1,1,1.21);n*=g.td(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.th(a,m,n);g.bh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;W4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",d5(this));e5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.ud(p+this.A,l),0!==t){u=this.stills[c];u||(u=new b5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var D=Math.floor(m*f/b),E=Math.floor(n*(k+t)/e)-z-4,F=Math.floor(m*(f+t)/b)-D-4;g.jh(u.element,D,z);g.th(u.element,F,E);g.bh(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1===t);g.L(u.element,"ytp-videowall-still-large",
2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.O(),z=g.nn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",W4(t,p,z),g.Ay(u)&&(u=p.ni(),u=g.fd(u,g.DC({},"emb_rel_end")),t.ia("url",u)),(p=(p=p.Ob)&&p.itct)&&g.DK(t.api,t.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ae(e.element),g.ne(e);this.stills.length=c}};
g.h.yH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=Ita(this,a),this.videoData=a,this.Dg())};
g.h.wH=function(){this.A+=this.stills.length;this.Dg()};
g.h.xH=function(){this.A-=this.stills.length;this.Dg()};
g.h.ky=function(){return!!this.u.w};
g.h.Zs=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Z4(this.u),this.Fa()&&this.Dg()):(this.C=!0,this.Fa()&&d5(this)&&(2===a?Y4(this.u):3===a&&$4(this.u)))};
g.h.vH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.FK(this.U,this.stills[a].element,!0);this.Zs(1)}else this.B=null,this.C=!1;this.Dg()};
g.h.Ys=function(){return this.Fa()&&d5(this)};g.r(f5,g.MK);g.h=f5.prototype;g.h.Ky=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Jta(this.player)||b;var c=a.dj||g.Jy(a.Qa),d=g.ZR(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Jy=function(){return this.endScreen.Ys()};
g.h.hG=function(){return this.Jy()?this.endScreen.ky():!1};
g.h.X=function(){g.NP(this.player.app,"endscreen",void 0);g.MK.prototype.X.call(this)};
g.h.load=function(){g.MK.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.MK.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.uH=function(a){this.Ky()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.PK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.OB=function(){g.NP(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.TC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.TC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.vK(this.player,[a,b])};g.aL.endscreen=f5;})(_yt_player);
