
server:
  port: 8181

spring:
  application:
    name: jwt-oauth-resource-server
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  jackson:
    serialization:
      INDENT_OUTPUT: true


security:
  jwt:
    public-key: classpath:public.txt