
spring:
  application:
    name: springboot-security
  datasource:
    #url: jdbc:h2:file:/data/demo
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
  h2:
  console:
    enabled: true #