
CREATE TABLE PERMISSION (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(60) UNIQUE KEY);

INSERT INTO PERMISSION (NAME) VALUES
('ROLE_CREATE'),
('ROLE_EDIT'),
('ROLE_DELETE'),
('ROLE_READ'),
('ROLE_READ_ALL');



CREATE TABLE ROLE
(ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(60) UNIQUE KEY);


INSERT INTO ROLE (NAME) VALUES
('ADMIN'),('USER');


CREATE TABLE PERMISSION_ROLE(
PERMISSION_ID INT,
FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION(ID),
ROLE_ID INT,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID));

INSERT INTO PERMISSION_ROLE (PERMISSION_ID, ROLE_ID) VALUES
(1,1),
(2,1),
(3,1),
(4,1),
(5,1),
(4,2),
(5,2);


CREATE TABLE USER (
ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(24) UNIQUE KEY NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
ENABLED BIT(1) NOT NULL,
ACCOUNT_EXPIRED BIT(1) NOT NULL,
CREDENTIALS_EXPIRED BIT(1) NOT NULL,
ACCOUNT_LOCKED BIT(1) NOT NULL);


INSERT INTO USER (
USERNAME,
PASSWORD,
EMAIL,
ENABLED,
ACCOUNT_EXPIRED,
CREDENTIALS_EXPIRED,
ACCOUNT_LOCKED) VALUES (
'adarsh',
'{bcrypt}$2a$10$srocXYXb5Bfst1U2nSgoJOUT3FXDxWndwzzVnxTuxLiAuffhFU/LG',
'adarsh@espark',
1,
0,
0,
0),
(
'radha',
'{bcrypt}$2a$10$zG8wDXX/hdywz.g.bFF7VOa4Lev8pEnMcygTuzQt18H0Ck7nJQf1S',
'radha@espark',
1,
0,
0,
0);

CREATE TABLE ROLE_USER (ROLE_ID INT,FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID),
USER_ID INT, FOREIGN KEY(USER_ID) REFERENCES USER(ID));


INSERT INTO ROLE_USER (ROLE_ID, USER_ID)VALUES
(1, 1) /* admin assigned to adarsh user */,
(2, 2) /* user assigned to radha user */ ;