logging:
  level:
    root: DEBUG

server:
  port: 9090

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:esparkDB
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

security:
  jwt:
    key-store: classpath:jwt.jks
    key-store-password: password
    key-pair-alias: jwt
    key-pair-password: password



