server:
  port: 8080

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/

espark.security.jwt.secret: otherpeopledontknowit
